apiVersion: v1
kind: Service
metadata:
  name: social-app-backend
  namespace: social-app
  annotations:
    # Attach the explicit GKE BackendConfig to adjust the behavior
    # of the external load balancer created by the Ingress.
    cloud.google.com/backend-config: '{"ports": {"80":"social-app-backend"}}'
spec:
  # Route traffic only to Pods created by the backend Deployment.
  selector:
    app: social-app-backend
  ports:
    - name: http
      # Expose a conventional HTTP port inside the cluster...
      port: 80
      # ...while forwarding requests to the Nest app listening on port 3000.
      targetPort: 3000
